---
title: "Interactive workshops"
author: "Mike Kleinsasser"
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
draft: false
menu:
  main:
    name: "Workshops"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Workshop series with interactive content for learning modern data science and statistics tools. We regularly create and share new content. Stay posted.

# Tidyverse series

Tidyverse is a collection of useful R packages for data science tasks. We've found them to be helpful, so we created and hosted a workshop series based on them.

### Visualize

It's hard to compete with ggplot2 when creating static visuals in R. Check out this interactive tutorial by following the link: [Learn ggplot2](https://umich-biostatistics.shinyapps.io/ggplot2_workshop/).

### Manipulate

Coming soon.

# High performance computing series

High performance computing, or HPC, is the process of tackling computationally intensive problems that are too big to run on a personal computer. This series introduces the user to techniques for executing large jobs both from a programming end and from the cluster computing perspective. This combination can lead to significantly improved performance.

## High performance R

Coming soon.
